// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormInfo: typeof import('./components/l-form/form-info.vue')['default']
    FormTooltip: typeof import('./components/l-form/form-tooltip.vue')['default']
    LAmap: typeof import('./components/l-amap/index.vue')['default']
    LDraggable: typeof import('./components/l-draggable/index.vue')['default']
    LEcharts: typeof import('./components/l-echarts/index.vue')['default']
    LEditor: typeof import('./components/l-editor/index.vue')['default']
    LEmpty: typeof import('./components/l-empty/index.vue')['default']
    LForm: typeof import('./components/l-form/index.vue')['default']
    LIframe: typeof import('./components/l-iframe/index.vue')['default']
    LIfyIcon: typeof import('./components/l-ify-icon/index.vue')['default']
    LQrcode: typeof import('./components/l-qrcode/index.vue')['default']
    LStatistic: typeof import('./components/l-statistic/index.vue')['default']
    LSvgIcon: typeof import('./components/l-svg-icon/index.vue')['default']
    LTable: typeof import('./components/l-table/index.vue')['default']
    LTableChoose: typeof import('./components/l-table-choose/index.vue')['default']
    LTableEdit: typeof import('./components/l-table-edit/index.vue')['default']
    LUploadFile: typeof import('./components/l-upload-file/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableContent: typeof import('./components/l-table/table-content.vue')['default']
    TableFooter: typeof import('./components/l-table/table-footer.vue')['default']
    TableSearch: typeof import('./components/l-table/table-search.vue')['default']
    TableToolbar: typeof import('./components/l-table/table-toolbar.vue')['default']
  }
}

export {}
